batch_size: 32
epochs: 50
fliplr: 0.01516
hsv_h: 0.011
hsv_s: 0.95
hsv_v: 0.45
img_size: 640
lr: 0.001
mixup: 0.4
momentum: 0.8
mosaic: 0.65
shear: 0.4
translate: 0.05
weight_decay: 0.0045
step_size: 3
gamma: 0.1
conf_threshold: 0.001
