batch_size: 64
epochs: 50
fliplr: 0.015
hsv_h: 0.011
hsv_s: 0.95
hsv_v: 0.45
img_size: 800
lr: 0.0002
mixup: 0
momentum: 0.8
mosaic: 0
shear: 0.4
translate: 0.05
weight_decay: 0.0045
step_size: 10
gamma: 0.1
