model_type: yolo

max_epochs: 100
batch_size: 64
width: 608
height: 608
channels: 3
momentum: 0.949
decay: 0.0005
angle: 0
saturation: 1.5
exposure: 1.5
hue: 0.1

learning_rate: 0.0025
burn_in: 1000
max_batches: 500500
policy: steps
steps: [400000, 450000]
scales: [0.1, 0.1]

mosaic: 1
cutmix: 1  

layers:
  - type: convolutional
    in_channels: 3
    out_channels: 64
    kernel_size: 7
    stride: 2
    padding: 3
    batch_norm: true
    activation: relu

  - type: convolutional
    in_channels: 64
    out_channels: 128
    kernel_size: 3
    stride: 1
    padding: 1
    batch_norm: true
    activation: relu

  - type: convolutional
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    stride: 1
    padding: 1
    batch_norm: true
    activation: relu

  - type: convolutional
    in_channels: 256
    out_channels: 512
    kernel_size: 3
    stride: 1
    padding: 1
    batch_norm: true
    activation: relu

  - type: convolutional
    in_channels: 512
    out_channels: 1024
    kernel_size: 3
    stride: 1
    padding: 1
    batch_norm: true
    activation: relu

  - type: convolutional
    in_channels: 1024
    out_channels: 1024
    kernel_size: 3
    stride: 1
    padding: 1
    batch_norm: true
    activation: relu

  - type: convolutional
    in_channels: 1024
    out_channels: 33
    kernel_size: 1
    stride: 1
    padding: 0
    batch_norm: false
    activation: linear
